title = "Worn-out Shoes"
baseurl = "https://greenonion.github.io/"
builddrafts = false
author = "Nikos Fertakis"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = true
languageCode = "en-us"
theme = "cocoa-eh"
disqusshortname = "greenonion-github-com"
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "2 Jan, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Thoughts"
copyright = "Copyright © 20[0-9]{2} Nikos Fertakis"
highlightjs = true
progressively = true
logofile = ""
latestpostcount = 5
lang = "en"
github = "greenonion"
email = "nikos.fertakis@gmail.com"
linkedin = "nfertakis"
twitter = "@nikosfertakis"
posts_navigation = true
disablefancyfonts = true
uselatex = true
highlightjslanguages = ["scheme", "clojure"]
